import type { Metadata } from "next";
import "./globals.css";
import NavBarItem from "./component/navbar/page";
import Footer from "./component/footer/page";


export const metadata: Metadata = {
  title: "Deploy Generative AI with NVIDIA",
  description: "Generated by create next app",
	openGraph: {
		title: "Deploy Generative AI with NVIDIA",
		description: "Generated by create next app",
		url: "https://www.nvidia.com/en-in/ai/",
		images:[
			{
				url: "/images/ai.jpeg",
				alt: "Generative AI"
			}
		]
	}
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<head>
				<title>Deploy Generative AI with NVIDIA</title>
			</head>
			<body>
				<NavBarItem />
					{children}
				<Footer />
			</body>
		</html>
	);
}
