import type { Metadata } from "next";
import "./globals.css";


// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title>Deploy Generative AI with NVIDIA</title>
      </head>
      <body>
        {children}
      </body>
    </html>
  );
}
