import type { Metadata } from "next";
import "./globals.css";
import NavBarItem from "./component/navbar/page";
import Footer from "./component/footer/page";


// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<head>
				<title>Deploy Generative AI with NVIDIA</title>
			</head>
			<body>
				<NavBarItem />
					{children}
				<Footer />
			</body>
		</html>
	);
}
